[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "prometheus-eaton-ups-exporter"
authors = [
    {name = "Mathis Lövenich"},
    {name = "Tobias Kadelka"},
]
description = "An Eaton UPS device metric exporter for Prometheus"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.11"
keywords = ["prometheus", "monitoring", "eaton", "ups"]
license = {file = "LICENSE.txt"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: ISC License (ISCL)",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Topic :: System :: Monitoring",
]
dependencies = [
    'httpx',
    'prometheus_client',
    'requests',
]

[project.urls]
repository = "https://github.com/psyinfra/prometheus-eaton-ups-exporter/"
issues = "https://github.com/psyinfra/prometheus-eaton-ups-exporter/issues"

[project.optional-dependencies]
tests = [
    'flake8',
    'pyre-check',
    'pytest == 7.2.1',
    'pytest-asyncio',
    'pytest-vcr',
]
dynamic = ["version"]

[project.scripts]
prometheus_eatonups_exporter = "prometheus_eaton_ups_exporter.main:main"

[tool.setuptools.dynamic]
version = {attr = "prometheus_eaton_ups_exporter.VERSION"}
